
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/static:/app/src/main/resources/static
    command: ["java", "-jar", "/app/target/your-springboot-app.jar"]
